[package]
name = "b"
version = "0.1.0"
authors = ["Alexander Willner <alex@willner.ws>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = { version = "0.7", default-features = false, features = ["simd"] }
# clap = "3.0.0-beta.1"